### ISSUE TITLE
Demonic sounds, Car flipping every turn, And car just dancing whenever it wants to.

### ISSUE THREAD

**Issue by Nerixuss** [PERRINN/project-424-unity#79]
Watch this video... Please.
https://youtu.be/8tBmYyHlK4U
Turn down your volume...
I'm not sure if this is just a bug or something but yeah..

(I'm now uploading it, give it some time.)

**Comment by Nerixuss** [comment]
https://youtu.be/8tBmYyHlK4U

**Comment by EdyJ** [comment]
Thanks for taking the time to record the video and report the issue. It's not a bug, just an incorrect setup of the the Unity project. Most likely you've copied the repository to an existing Unity project, instead of opening the repository folder directly in Unity.

Most evident issue is the wrong physics rate: _Project > Settings > Time > Fixed Timestep_ must be 0.002 (500 Hz). Default is 0.02 (50 Hz). The 424 uses very high spring and damper rates in the suspension, which require a high physics frequency to be simulated properly in Unity. When the physics frequency is as low as the default, the underlying physics engine (PhysX) responds badly to these suspension settings, so the car bounces and flips without control.

It's true that the audio may be a bit loud, but the sound is pretty close to what an actual electric racing car sounds like. In this case the 424 has two very powerful MGUs (Motor Generator Units), each one producing its sound independently.

Also note that currently the 424 simulation is intended to be driven either with the autopilot (`Q` key) or with a steering wheel device with pedals (`I` key to configure). Keyboard controls don't provide any steering or input assistance.

**Comment by EdyJ** [comment]
I've added detailed instructions to the README on how to setup the repository correctly in Unity

**Comment by Nerixuss** [comment]
Thanks!
